package verify_test

// fixtures_test.go — round-trip tests for RSA-PSS and ECDSA fixture files.
//
// The fixture files under testdata/ are generated by:
//
//	go run ./internal/verify/testdata/gen
//
// If the files do not exist (first run, or after a clean checkout), this test
// generates them on-the-fly into a temp directory and verifies them, proving
// the full parse→verify pipeline works end-to-end for real BYOK receipts.

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/deja-dev/dsr-verifier-cli/internal/dsr"
	"github.com/deja-dev/dsr-verifier-cli/internal/verify"
)

// fixtureReceipt holds the data needed to write a fixture receipt + key pair.
type fixtureReceipt struct {
	ReceiptPath string
	KeyPath     string
}

// generateRSAPSSFixture writes a real RSA-PSS signed receipt and key file into dir.
// How generated:
//   - Key: rsa.GenerateKey(rand.Reader, 2048) → PKIX PEM
//   - Sig: rsa.SignPSS(rand.Reader, priv, crypto.SHA256, sha256(payload), PSSSaltLengthAuto)
func generateRSAPSSFixture(t *testing.T, dir string) fixtureReceipt {
	t.Helper()
	const algo = "rsa-pss-sha256"
	const keyID = "key_fixture_rsa_pss_2026"
	const receiptID = "r_fixture_rsa_pss_001"

	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("rsa.GenerateKey: %v", err)
	}

	content, contentHash, issuedAt := sharedFixtureContent()
	payload := buildFixturePayload(t, receiptID, algo, keyID, contentHash, issuedAt)

	hashed := sha256.Sum256(payload)
	opts := &rsa.PSSOptions{SaltLength: rsa.PSSSaltLengthAuto, Hash: crypto.SHA256}
	sig, err := rsa.SignPSS(rand.Reader, priv, crypto.SHA256, hashed[:], opts)
	if err != nil {
		t.Fatalf("rsa.SignPSS: %v", err)
	}

	keyPath := filepath.Join(dir, "rsa_pss_key.pub")
	receiptPath := filepath.Join(dir, "rsa_pss_receipt.dsr")
	writeFixturePEMKey(t, keyPath, &priv.PublicKey, keyID)
	writeFixtureReceipt(t, receiptPath, receiptID, algo, keyID, contentHash, content, issuedAt, sig)

	return fixtureReceipt{ReceiptPath: receiptPath, KeyPath: keyPath}
}

// generateECDSAFixture writes a real ECDSA signed receipt and key file into dir.
// How generated:
//   - Key: ecdsa.GenerateKey(elliptic.P256(), rand.Reader) → PKIX PEM
//   - Sig: ecdsa.SignASN1(rand.Reader, priv, sha256(payload)) → DER-encoded
func generateECDSAFixture(t *testing.T, dir string) fixtureReceipt {
	t.Helper()
	const algo = "ecdsa-sha256"
	const keyID = "key_fixture_ecdsa_2026"
	const receiptID = "r_fixture_ecdsa_001"

	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("ecdsa.GenerateKey: %v", err)
	}

	content, contentHash, issuedAt := sharedFixtureContent()
	payload := buildFixturePayload(t, receiptID, algo, keyID, contentHash, issuedAt)

	hashed := sha256.Sum256(payload)
	// ecdsa.SignASN1 produces DER-encoded output — same encoding used by AWS KMS.
	sig, err := ecdsa.SignASN1(rand.Reader, priv, hashed[:])
	if err != nil {
		t.Fatalf("ecdsa.SignASN1: %v", err)
	}

	keyPath := filepath.Join(dir, "ecdsa_key.pub")
	receiptPath := filepath.Join(dir, "ecdsa_receipt.dsr")
	writeFixturePEMKey(t, keyPath, &priv.PublicKey, keyID)
	writeFixtureReceipt(t, receiptPath, receiptID, algo, keyID, contentHash, content, issuedAt, sig)

	return fixtureReceipt{ReceiptPath: receiptPath, KeyPath: keyPath}
}

// sharedFixtureContent returns stable content fields shared across BYOK fixtures.
func sharedFixtureContent() (content json.RawMessage, contentHash string, issuedAt time.Time) {
	content = json.RawMessage(`{"commit_sha":"fixture000000000000000000000000000000000000","merged_at":"2026-05-01T00:00:00Z","pr_url":"github.com/deja-dev/example#1"}`)
	sum := sha256.Sum256(content)
	contentHash = hex.EncodeToString(sum[:])
	issuedAt = time.Date(2026, 5, 1, 0, 0, 0, 0, time.UTC)
	return
}

// buildFixturePayload constructs the canonical signed payload for a fixture receipt.
func buildFixturePayload(t *testing.T, id, algo, keyID, contentHash string, issuedAt time.Time) []byte {
	t.Helper()
	partial := &dsr.Receipt{
		ID:               id,
		Version:          dsr.Version,
		Type:             dsr.TypeR1,
		VaultID:          "vlt_fixture_byok",
		IssuedAt:         issuedAt,
		ContentHash:      contentHash,
		SigningKeyID:     keyID,
		SigningAlgorithm: algo,
	}
	payload, err := dsr.CanonicalSignedPayload(partial)
	if err != nil {
		t.Fatalf("CanonicalSignedPayload: %v", err)
	}
	return payload
}

func writeFixturePEMKey(t *testing.T, path string, pub interface{}, keyID string) {
	t.Helper()
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		t.Fatalf("MarshalPKIXPublicKey: %v", err)
	}
	block := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der})
	data := fmt.Sprintf("# key_id: %s\n%s", keyID, string(block))
	if err := os.WriteFile(path, []byte(data), 0644); err != nil {
		t.Fatalf("WriteFile(%s): %v", path, err)
	}
}

func writeFixtureReceipt(t *testing.T, path, id, algo, keyID, contentHash string, content json.RawMessage, issuedAt time.Time, sig []byte) {
	t.Helper()
	receipt := map[string]interface{}{
		"id":                id,
		"version":           dsr.Version,
		"type":              dsr.TypeR1,
		"vault_id":          "vlt_fixture_byok",
		"issued_at":         issuedAt.UTC().Format(time.RFC3339),
		"content":           content,
		"content_hash":      contentHash,
		"signing_key_id":    keyID,
		"signing_algorithm": algo,
		"signature":         hex.EncodeToString(sig),
	}
	b, err := json.MarshalIndent(receipt, "", "  ")
	if err != nil {
		t.Fatalf("json.MarshalIndent: %v", err)
	}
	if err := os.WriteFile(path, b, 0644); err != nil {
		t.Fatalf("WriteFile(%s): %v", path, err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Test: RSA-PSS fixture file round-trip
// ─────────────────────────────────────────────────────────────────────────────

func TestRSAPSSFixtureRoundtrip(t *testing.T) {
	dir := t.TempDir()
	fx := generateRSAPSSFixture(t, dir)

	receiptData, err := os.ReadFile(fx.ReceiptPath)
	if err != nil {
		t.Fatalf("ReadFile receipt: %v", err)
	}
	keyData, err := os.ReadFile(fx.KeyPath)
	if err != nil {
		t.Fatalf("ReadFile key: %v", err)
	}

	r, parseErr := dsr.Parse(receiptData)
	if parseErr != nil {
		t.Fatalf("Parse RSA-PSS fixture: %v", parseErr)
	}
	if r.SigningAlgorithm != dsr.SigningAlgorithmRSAPSS {
		t.Errorf("SigningAlgorithm = %q, want %q", r.SigningAlgorithm, dsr.SigningAlgorithmRSAPSS)
	}

	provided, keyErr := verify.ParsePublicKeyFile(keyData)
	if keyErr != nil {
		t.Fatalf("ParsePublicKeyFile (RSA fixture): %v", keyErr)
	}

	if res := verify.KeyAuthority(r, provided); !res.Valid {
		t.Errorf("KeyAuthority: %v", res.Err)
	}
	if res := verify.Signature(r, provided); !res.Valid {
		t.Errorf("Signature: %v", res.Err)
	}
	if res := verify.ContentHash(r); !res.Valid {
		t.Errorf("ContentHash: %v", res.Err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Test: ECDSA fixture file round-trip
// ─────────────────────────────────────────────────────────────────────────────

func TestECDSAFixtureRoundtrip(t *testing.T) {
	dir := t.TempDir()
	fx := generateECDSAFixture(t, dir)

	receiptData, err := os.ReadFile(fx.ReceiptPath)
	if err != nil {
		t.Fatalf("ReadFile receipt: %v", err)
	}
	keyData, err := os.ReadFile(fx.KeyPath)
	if err != nil {
		t.Fatalf("ReadFile key: %v", err)
	}

	r, parseErr := dsr.Parse(receiptData)
	if parseErr != nil {
		t.Fatalf("Parse ECDSA fixture: %v", parseErr)
	}
	if r.SigningAlgorithm != dsr.SigningAlgorithmECDSA {
		t.Errorf("SigningAlgorithm = %q, want %q", r.SigningAlgorithm, dsr.SigningAlgorithmECDSA)
	}

	provided, keyErr := verify.ParsePublicKeyFile(keyData)
	if keyErr != nil {
		t.Fatalf("ParsePublicKeyFile (ECDSA fixture): %v", keyErr)
	}

	if res := verify.KeyAuthority(r, provided); !res.Valid {
		t.Errorf("KeyAuthority: %v", res.Err)
	}
	if res := verify.Signature(r, provided); !res.Valid {
		t.Errorf("Signature: %v", res.Err)
	}
	if res := verify.ContentHash(r); !res.Valid {
		t.Errorf("ContentHash: %v", res.Err)
	}
}
